### ISSUE TITLE
Unable to silence logging of SFTPretty

### ISSUE THREAD

**Issue by AetherBreaker** [byteskeptical/sftpretty#62]
Digging around through your code, the _start_transport method of the Connection class calls `self._transport.set_log_channel(host)`

This method creates a logger who's parent is the root logger.
This causes any and all attempts to silence logging on a per library basis `logging.getLogger("SFTPretty").setLevel(logging.WARNING)`
`logging.getLogger("paramiko").setLevel(logging.WARNING)`

To fail to silence most logs as the newly created channel log inherits its log level from the root logger.

**Comment by byteskeptical** [comment]
You're running into that issue because you need to apply that change to the transport itself instead of the threaded channels created afterwards. You can set this either as a CnOpts.log_level or in your ssh config. There is the consideration of keeping parity with the underlying sshd_config LogLevel directive which doesn't have a warn level. This along with my own assumptions about usage in general is the reason support was never even added. That being said I just pushed a PR adding a mapping for the WARN/WARNING log level in general along with support for setting the log level in CnOpts directly to the int value equivalent of the logging.{DEBUG, ERRROR, INFO, WARN} variables. 

```
     LogLevel
             Gives the verbosity level that is used when logging messages from
             sshd(8).  The possible values are: QUIET, FATAL, ERROR, INFO,
             VERBOSE, DEBUG, DEBUG1, DEBUG2, and DEBUG3.  The default is INFO.
             DEBUG and DEBUG1 are equivalent.  DEBUG2 and DEBUG3 each specify
             higher levels of debugging output.  Logging with a DEBUG level
             violates the privacy of users and is not recommended.
```


```python
    cnopts = CnOpts(knownhosts='aetherbreaker.pub')
    # Turn off most logging and set custom log file
    cnopts.log = '/var/log/aetherbreaker.log'
    cnopts.log_level = 'warn' or cnopts.log_level = 30
    # Pass options object directly to connection object
    with Connection('hostname', cnopts=cnopts, private_key='~/.ssh/id_breaker',
                    private_key_pass='supersecret') as sftp:
```

**Comment by AetherBreaker** [comment]
When I was doing my testing for this issue, I actually had the log level in my cnopts set to ERROR. Despite this, when peering into the LogDict, the logging level of the channel logger was still being set to DEBUG (the level of my root logger).

I'll try and verify this and provide my code tomorrow. All the code I was working on is saved locally on my work PC.

**Comment by byteskeptical** [comment]
Perhaps I'm misunderstanding the issue but this is what I'm seeing and testing.

![Image](https://github.com/user-attachments/assets/6e24ff8c-2d65-488f-aa0c-cda58e19a328)

**Comment by byteskeptical** [comment]
Unless you have an objection I'm going to merge the PR which will close this issue. If you find something I missed after we can always revisit this.

**Comment by neurino** [comment]
I'm still getting a lot of info entries in my logs (se below) despite setting `log_level = 'warning'` in **all** my connections subclassing Connection directly

```
class Connection(sftpretty.Connection):
    _cnopts = sftpretty.CnOpts(knownhosts='known_hosts')
    def __init__(self, host, cnopts=_cnopts, *args, **kwargs):
        cnopts.log_level = 'warning'
        super().__init__(host, cnopts=cnopts, *args, **kwargs)

```

[I see in the code](https://github.com/byteskeptical/sftpretty/blob/root/sftpretty/__init__.py#L250) this:

    level = self._config.get('loglevel') or self._cnopts.log_level

is `_cnopts` even took into consideration if somehow loglevel is already in `_config`?

Sample of my logs: 14 entries for a single file transfer

```
INFO 2025-11-18T20:00:26.368989Z Transfer of File: [doc.pdf] @ 7.5% 32768:439688 bytes
INFO 2025-11-18T20:00:26.389246Z Transfer of File: [doc.pdf] @ 14.9% 65536:439688 bytes
INFO 2025-11-18T20:00:26.389895Z Transfer of File: [doc.pdf] @ 22.4% 98304:439688 bytes
INFO 2025-11-18T20:00:26.390815Z Transfer of File: [doc.pdf] @ 29.8% 131072:439688 bytes
INFO 2025-11-18T20:00:26.391506Z Transfer of File: [doc.pdf] @ 37.3% 163840:439688 bytes
INFO 2025-11-18T20:00:26.392327Z Transfer of File: [doc.pdf] @ 44.7% 196608:439688 bytes
INFO 2025-11-18T20:00:26.393251Z Transfer of File: [doc.pdf] @ 52.2% 229376:439688 bytes
INFO 2025-11-18T20:00:26.394015Z Transfer of File: [doc.pdf] @ 59.6% 262144:439688 bytes
INFO 2025-11-18T20:00:26.394770Z Transfer of File: [doc.pdf] @ 67.1% 294912:439688 bytes
INFO 2025-11-18T20:00:26.395440Z Transfer of File: [doc.pdf] @ 74.5% 327680:439688 bytes
INFO 2025-11-18T20:00:26.395999Z Transfer of File: [doc.pdf] @ 82.0% 360448:439688 bytes
INFO 2025-11-18T20:00:26.397050Z Transfer of File: [doc.pdf] @ 89.4% 393216:439688 bytes
INFO 2025-11-18T20:00:26.397586Z Transfer of File: [doc.pdf] @ 96.9% 425984:439688 bytes
INFO 2025-11-18T20:00:26.474377Z Transfer of File: [doc.pdf] @ 100.0% 439688:439688 bytes
```
